/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['ng-select {\n    box-sizing: border-box;\n    display: inline-block;\n    margin: 0;\n    position: relative;\n    vertical-align: middle;\n    width: 100%;\n\n    // Container.\n    >div {\n        border: 1px solid #ececec;\n        cursor: pointer;\n        height: 30px;\n        user-select: none;\n        width: 100%;\n\n        &.open {\n\n        }\n\n        &.focus {\n\n        }\n\n        &.below {\n\n        }\n\n        &.multiple {\n\n        }\n\n        >div.single {\n            display: flex;\n            height: 100%;\n            width: 100%;\n\n            >div.value {\n                flex: 1;\n            }\n\n            >div.clear {\n                width: 30px;\n\n                &:hover {\n                    background-color: #ececec;\n                }\n            }\n\n            >div.arrow {\n                width: 30px;\n            }\n        }\n    }\n}\n'];